version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/peddlers-customers-frontend
permissions:
  - object: /tmp/peddlers-customers-frontend
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      runas: ubuntu