pipelines:
  branches:
    master:
      - step:
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --region eu-west-1 --application-name gs3-prod --s3-location s3://gs3-prod-codedeploy/peddlers-customers-frontend.zip
    staging:
      - step:
          image: atlassian/pipelines-awscli
          script:
            - aws deploy push --region us-east-1 --application-name gs3-staging --s3-location s3://gs3-staging-codedeploy/peddlers-customers-frontend-staging.zip
