//MESSAGES
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const GET_LATEST_PRODUCTS = 'GET_LATEST_PRODUCTS';
export const LOADING_LATEST_PRODUCTS = 'LOADING_LATEST_PRODUCTS';
export const GET_TOP_PRODUCTS = 'GET_TOP_PRODUCTS';
export const LOADING_TOP_PRODUCTS = 'LOADING_TOP_PRODUCTS';
